include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for IPTV
LUCI_DEPENDS:=+iptv
LUCI_PKGARCH:=all

PKG_LICENSE:=AGPL-3.0-only
PKG_MAINTAINER:=iptv-rs maintainers

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
